/userfs/bin/iwpriv ra1 set CountryRegion=1
/userfs/bin/iwpriv ra1 set Channel=1
/userfs/bin/iwpriv ra1 set BeaconPeriod=100
/userfs/bin/iwpriv ra1 set RTSThreshold=2347
/userfs/bin/iwpriv ra1 set FragThreshold=2346
/userfs/bin/iwpriv ra1 set DtimPeriod=1
/userfs/bin/iwpriv ra1 set IgmpSnEnable=1
/userfs/bin/iwpriv ra1 set AutoChannelDisable=1
/userfs/bin/iwpriv ra1 set PercentageCtrl=1
/userfs/bin/iwpriv ra1 set PowerDropCtrl=100
/userfs/bin/iwpriv ra1 set HtBssCoex=0
/userfs/bin/iwpriv ra1 set WirelessMode=16
/userfs/bin/iwpriv ra1 set BasicRate=15
/userfs/bin/iwpriv ra1 set HtBw=1
/userfs/bin/iwpriv ra1 set HtExtcha=1
/userfs/bin/iwpriv ra1 set HtGi=1
/userfs/bin/iwpriv ra1 set HtMcs=33
/userfs/bin/iwpriv ra1 set HideSSID=0
/userfs/bin/iwpriv ra1 set AuthMode=WPA2PSK
/userfs/bin/iwpriv ra1 set EncrypType=AES
/userfs/bin/iwpriv ra1 set SSID="Pirat 2.4G"
/userfs/bin/iwpriv ra1 set WPAPSK="56456740"
/userfs/bin/iwpriv ra1 set DefaultKeyID=2
/userfs/bin/iwpriv ra1 set AccessPolicySky=0
/userfs/bin/iwpriv ra1 set WscConfStatus=2
/userfs/bin/iwpriv ra1 set WscConfMode=7
/userfs/bin/iwpriv ra1 set SSID="Pirat 2.4G"
/userfs/bin/iwpriv ra1 set MbssMaxStaNum=64
