LowRSSIAPSteerEdge_RE=33
CUOverloadTh_2G=100
CUOverloadTh_5G_L=100
CUOverloadTh_5G_H=100
PHYBasedSelection=0
MCSRateXingThreshold_DG=50
MCSRateXingThreshold_UG=122880
RSSISteeringEdge_DG=21
RSSISteeringEdge_UG=25
LowRSSIAPSteerEdge_root=33
ActivityThreshold=20971520
SteeringProhibitTime=45
BTMSteeringProhibitTime=30
SteeringUnfriendlyTime=60
BTMUnfriendlyTime=60
reset_btm_csbc_at_join=1
SteeringDetectInterval=3
disable_force_strng=1
disable_force_strng_11v_cli=1
measure_11k_threshold=25
ignore_steer_window=0
SteeringDetectInterval=3
update_2g_ch_without_probe_req=1
update_5g_ch_without_probe_req=1
MetricRepIntv=10
MetricPolicyChUtilThres_24G=0
MetricPolicyChUtilThres_5GL=0
MetricPolicyChUtilThres_5GH=0
ChPlanningChUtilThresh_24G=100
ChPlanningChUtilThresh_5GL=100
ChPlanningEDCCAThresh_24G=255
ChPlanningEDCCAThresh_5GL=255
ChPlanningOBSSThresh_24G=255
ChPlanningOBSSThresh_5GL=255
ChPlanningR2MonitorTimeoutSecs=300
ChPlanningR2MetricReportingInterval=10
ChPlanningR2MinScoreMargin=80
MetricPolicyRcpi_24G=0
MetricPolicyRcpi_5GL=0
MetricPolicyRcpi_5GH=0
