v8021PEnable=No
Active=Yes
ServiceList=INTERNET
BandActive=N/A
LAN1=No
LAN2=No
LAN3=No
LAN4=No
SSID2=No
SSID3=No
SSID4=No
SSID5=No
SSIDAC2=No
SSIDAC3=No
SSIDAC4=Yes
SSIDAC5=No
WanMode=Bridge
LinkMode=linkPPP
BridgeMode=IP_Bridged
DHCPRealy=Yes
IPVERSION=IPv4
ISP=3
VLANMode=TAG
dot1q=Yes
VLANID=293
dot1p=Yes
dot1pData=0
DOT1P=0
MulticastVID=
NATENABLE=Disabled
IGMPproxy=No
DHCPv6=No
GW6_Manual=No
IFIdx=2
DsliteEnable=No
PDEnable=No
DHCPv6PD=No
PDOrigin=None
DHCPEnable=0
BridgeInterface=
THSI=1
PPPManualStatus=disconnect
ConnectionError=ERROR_NO_ANSWER
NASName=nas1_0
IFName=nas1_0
uptime_sec=58
uptime_nsec=124921000
uptime6_sec=58
uptime6_nsec=124921000
