v8021PEnable=No
Active=Yes
ServiceList=TR069_INTERNET
BandActive=N/A
LAN1=Yes
LAN2=Yes
LAN3=Yes
LAN4=Yes
LAN25G=Yes
SSID2=Yes
SSID3=Yes
SSID4=Yes
SSID5=Yes
SSIDAC2=Yes
SSIDAC3=Yes
SSIDAC4=No
SSIDAC5=Yes
WanMode=Route
LinkMode=linkPPP
MTU=1492
PPPGETIP=Dynamic
CONNECTION=Connect_Keep_Alive
USERNAME=6420e19e3242@truehisp
PASSWORD=password
SRVNAME=
PPPManualStatus=disconnect
IPVERSION=IPv4/IPv6
ISP=2
VLANMode=TAG
dot1q=Yes
VLANID=100
dot1p=Yes
dot1pData=0
DOT1P=0
MulticastVID=
NATENABLE=Enable
IGMPproxy=No
DHCPv6=No
GW6_Manual=No
IFIdx=1
DsliteEnable=No
DsliteMode=0
PDEnable=Yes
DHCPv6PD=Yes
PDOrigin=PrefixDelegation
DHCPEnable=1
BridgeInterface=
tr69_wanidx=1
tr69_entryidx=1
ConnectionError=ERROR_NO_ANSWER
NASName=nas0_0
IFName=ppp0
