interface ppp0 {
	send ia-pd 213;
	request domain-name;
	request domain-name-servers;
	script "/usr/script/dhcp6c_script";
	request vendor_opts;
};
id-assoc pd 213 {
	prefix-interface br0
	{
		sla-len 0;
	};
};
